version: '3'  # Version of docker-compose being used
services:
  
  # Book Catalog Microservice
  book_catalog:
    image: book_catalog:latest  # Using the latest version of the book_catalog image
    build: 
      context: ./book_catalog  # Context to build the Dockerfile from the book_catalog directory
      dockerfile: Dockerfile  # Specifies which Dockerfile to use for building the image
      args:
        - NO_CACHE=true  # No cache during the build process to ensure fresh builds
    container_name: book_catalog_cntr  # Name of the container in Docker for easier identification
    ports:
      - "6002:5000"  # Mapping external port 6002 to internal container port 5000
    environment:
      - PORT=5000  # Specifies the port the application listens to within the container
      - DATABASE_URL=postgresql://admin:t0SD9o3rcx4xkbTkhKJMzIzvl2ffgkgO@dpg-crfo9u2j1k6c7396ag80-a.oregon-postgres.render.com/library_db_3xdg  # Database connection string
    restart: unless-stopped  # Restarts the container unless it is explicitly stopped

  # Inventory Management Microservice
  inventory_management:
    image: inventory_management:latest  # Using the latest version of the inventory_management image
    build: 
      context: ./inventory_management  # Context to build the Dockerfile from the inventory_management directory
      dockerfile: Dockerfile  # Specifies which Dockerfile to use for building the image
      args:
        - NO_CACHE=true  # No cache during the build process to ensure fresh builds
    container_name: inventory_management_cntr  # Name of the container in Docker for easier identification
    ports:
      - "6003:5001"  # Mapping external port 6003 to internal container port 5001
    environment:
      - PORT=5001  # Specifies the port the application listens to within the container
      - DATABASE_URL=postgresql://admin:t0SD9o3rcx4xkbTkhKJMzIzvl2ffgkgO@dpg-crfo9u2j1k6c7396ag80-a.oregon-postgres.render.com/library_db_3xdg  # Database connection string
    restart: unless-stopped  # Restarts the container unless it is explicitly stopped
